create table "public"."Projects" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "description" text not null
);


alter table "public"."Projects" enable row level security;

CREATE UNIQUE INDEX "Projects_pkey" ON public."Projects" USING btree (id);

alter table "public"."Projects" add constraint "Projects_pkey" PRIMARY KEY using index "Projects_pkey";

grant delete on table "public"."Projects" to "anon";

grant insert on table "public"."Projects" to "anon";

grant references on table "public"."Projects" to "anon";

grant select on table "public"."Projects" to "anon";

grant trigger on table "public"."Projects" to "anon";

grant truncate on table "public"."Projects" to "anon";

grant update on table "public"."Projects" to "anon";

grant delete on table "public"."Projects" to "authenticated";

grant insert on table "public"."Projects" to "authenticated";

grant references on table "public"."Projects" to "authenticated";

grant select on table "public"."Projects" to "authenticated";

grant trigger on table "public"."Projects" to "authenticated";

grant truncate on table "public"."Projects" to "authenticated";

grant update on table "public"."Projects" to "authenticated";

grant delete on table "public"."Projects" to "service_role";

grant insert on table "public"."Projects" to "service_role";

grant references on table "public"."Projects" to "service_role";

grant select on table "public"."Projects" to "service_role";

grant trigger on table "public"."Projects" to "service_role";

grant truncate on table "public"."Projects" to "service_role";

grant update on table "public"."Projects" to "service_role";


